name: scouts_and_guides
description: "A new Flutter application."
publish_to: 'none'

version: 4.0.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # AdMob & Storage
  google_mobile_ads: ^8.0.0
  shared_preferences: ^2.2.2

  # Video Playback
  video_player: ^2.8.2
  chewie: ^1.14.1

  audioplayers: ^6.0.0

  # Premium UI Fonts
  google_fonts: ^8.1.0

  # Firebase Core & Auth
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0000C8"
  adaptive_icon_foreground: "assets/images/appicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/audio/